AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Tracing: Active
    Timeout: 20
  Api:
    TracingEnabled: True

Resources:

  UserTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: momento-demo-users
      PrimaryKey:
        Name: id
        Type: String

  Function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src
      Handler: app.handler
      Runtime: nodejs16.x
      MemorySize: 2048
      Policies:
        - AWSXrayWriteOnlyAccess
        - DynamoDBCrudPolicy:
            TableName: !Ref UserTable
      Events:
        CreateUser:
          Type: Api
          Properties:
            Path: /bootstrap-users
            Method: POST
        GetUser:
          Type: Api
          Properties:
            Path: /users
            Method: GET
        GetCachedUser:
          Type: Api
          Properties:
            Path: /cached-users
            Method: GET
        GetFollowers:
          Type: Api
          Properties:
            Path: /followers
            Method: GET
        GetCachedFollowers:
          Type: Api
          Properties:
            Path: /cached-followers
            Method: GET
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: false
        Target: "es2020"
        Sourcemap: true
        EntryPoints:
          - app.ts

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  Api:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"
  FunctionArn:
    Value: !GetAtt Function.Arn
